// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeXsI6e4IF52Wta0kKAnRF--pxni9mOPo',
    appId: '1:325788857053:web:be75fcef463f19cfc6a134',
    messagingSenderId: '325788857053',
    projectId: 'kakuro-6d6f4',
    authDomain: 'kakuro-6d6f4.firebaseapp.com',
    storageBucket: 'kakuro-6d6f4.appspot.com',
    measurementId: 'G-GVN0222NCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnWIHnolrpW0kfDVEzFSXBDmvXPQYm5VQ',
    appId: '1:325788857053:android:28db2ff8bf664c1cc6a134',
    messagingSenderId: '325788857053',
    projectId: 'kakuro-6d6f4',
    storageBucket: 'kakuro-6d6f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFBby7y6f8A6PBqrpM9XpIJD_Z7UBpVA',
    appId: '1:325788857053:ios:1879dc2b1dadec5cc6a134',
    messagingSenderId: '325788857053',
    projectId: 'kakuro-6d6f4',
    storageBucket: 'kakuro-6d6f4.appspot.com',
    androidClientId: '325788857053-vfsav80fngdlkblvurgs0oitcbilpstt.apps.googleusercontent.com',
    iosClientId: '325788857053-5opss9vlhni2ebuvsrc9mpqq2j0kngru.apps.googleusercontent.com',
    iosBundleId: 'com.loutre.kakuro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQFBby7y6f8A6PBqrpM9XpIJD_Z7UBpVA',
    appId: '1:325788857053:ios:1879dc2b1dadec5cc6a134',
    messagingSenderId: '325788857053',
    projectId: 'kakuro-6d6f4',
    storageBucket: 'kakuro-6d6f4.appspot.com',
    androidClientId: '325788857053-vfsav80fngdlkblvurgs0oitcbilpstt.apps.googleusercontent.com',
    iosClientId: '325788857053-5opss9vlhni2ebuvsrc9mpqq2j0kngru.apps.googleusercontent.com',
    iosBundleId: 'com.loutre.kakuro',
  );
}
